apiVersion: v1
kind: Service
metadata:
  name: mcp-sasviya-api-service
spec:
  type: NodePort
  selector:
    app: mcp-sasviya-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080