apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-sasviya-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-sasviya-api
  template:
    metadata:
      labels:
        app: mcp-sasviya-api
    spec:
      containers:
      - name: mcp-sasviya-api
        image: mcp-sasviya-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000